import Head from "next/head";
import Card from "../components/Card";
import Header from "../components/Header";
import { ContainerCards } from "../components/_ui/ContainerCards";

export default function Home() {
   return (
      <>
         <Head>
            <title>Movies</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <Header />

         <ContainerCards>
            <Card />
            <Card />
            <Card />
         </ContainerCards>
      </>
   );
}
